### ISSUE TITLE
Healthbar should use offsets in json file

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/ragin-mages#107]
Player health bars should use the offsets listed in characters.json.  The offsets should be adjusted for the sprites to display correctly.

Do we want the health bars just below the name as currently done or below character?

**Comment by ignacioxd** [comment]
I think between the character and the player name works. What do you think? In most games the health bar is over the character.

**Comment by AtlantaDancer** [comment]
over the character works.
