### ISSUE TITLE
Service worker fails when set to 'update on reload'

### ISSUE THREAD

**Issue by adnanusman** [ignacioxd/ragin-mages#118]
When the option for the service worker to reload is set active, the website fails to load. 

The error in the console is:

The FetchEvent for "https://raginmages.net/" resulted in a network error response: an object that was not a Response was passed to respondWith().

**Comment by adnanusman** [comment]
I'm looking into it.

**Comment by PepperAddict** [comment]
![swerror](https://user-images.githubusercontent.com/4171505/38449723-07094bf4-39e1-11e8-8cd6-8471315b8296.png)

Here's the screenshot of the error to refer back to.

**Comment by adnanusman** [comment]
Thanks @PepperAddict :)

**Comment by adnanusman** [comment]
I was looking into this today and tried to replicate issue.... Doesn't seem to happen any more. Page reloads fine in 'update on reload' mode. Can anyone else verify please?
