### ISSUE TITLE
HUDs and Menus

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/ragin-mages#19]
We need a way to display in-game dialogs. We can start with something simple like pressing a key to show the instructions and clicking on a button on the dialog to close it.

**Comment by scottwestover** [comment]
If no one else has started on this, I will start on the dialog modal.

**Comment by scottwestover** [comment]
Added #23 for this.

**Comment by ignacioxd** [comment]
This PR has been merged! Thanks. Really nice job.

To close this issue, we should use one of these dialogs to replace the HTML overlay with instructions.

**Comment by AtlantaDancer** [comment]
Besides the modal dialog do we want a non-modal HUD at the top of the screen showing playerName/Tag, health, score, status(live, dead, spawning...)?  If so we can open a separate issue and I can work on it. Not sure if we want the status or not.  Initially can be a text display then we can enhance with pictures - hearts for status, etc. if we want.

**Comment by ignacioxd** [comment]
I was thinking the health bar should be displayed right on top of each player and follow them as they move around, but I'm not sure how that would be implemented.

We still need non-modal HUDs to show things like kill streak and a button to quit the arena and go back. Feel free to open issues that you think are missing or useful to have.
