### ISSUE TITLE
Service worker should cache all the files defined in the assets.json manifest

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/ragin-mages#45]
We have an asset manifest file (`assets.json`) that contains all of the assets the game requires, and also includes supporting files to be cached (e.g., `index.html`, CSS, etc.) The service worker should use this file to determine what to cache, as opposed to having hard-coded file paths.

It might be useful in some cases to use the `util/ServiceWorker.js` file to post a message to `sw.js` passing in the manifest object that the game already loads. The service worker could also load the manifest directly as a first step.

**Comment by adnanusman** [comment]
I'd like to work on this
