### ISSUE TITLE
Add HP/health bar to game screen

### ISSUE THREAD

**Issue by flaura42** [ignacioxd/ragin-mages#69]
I will be working on this with a new member to our group, kySuga.  We will also be working on adding HP functionality to the game.

**Comment by ignacioxd** [comment]
It would be nice if this health bar could be displayed over each player as they move around, so that everyone knew each other's health.

**Comment by PepperAddict** [comment]
How is this going, Laura? Do you want someone else to work on this?

**Comment by flaura42** [comment]
Ignacioxd has had me trying to figure out how to implement the healthbar displaying overhead.  So far, I've only found examples of it with the previous Phaser version and/or available as a paid plugin.  It must be possible...
