### ISSUE TITLE
User reentering game has ghost

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/ragin-mages#86]
noticed during development.  After user is killed if they select "exit game" then chooses a new character and re-enters multi-player battle the old character is still on the field.  They aren't removed from "existing players" list, and gets added as a new player.

Steps to recreate:
1. enter multi-player battle
2. get kiled
3. at "exit"/ respawn dialog choose to exit game
4. choose new character and enter multi-player battle
5. you will see old character and new character on the battle field
    - if you have console open it will show 2 players instead of 1 player (or 1 higher that actual players)

**Comment by AtlantaDancer** [comment]
I am in this section of code looking at the leader board so you can assign this issue to me.

Once I solve it do you want a separate pull request for this or include in the leader board changes?

**Comment by ignacioxd** [comment]
A separate pull request would be ideal. Thanks for asking!

**Comment by ignacioxd** [comment]
I think this issue has been fixed as part of a networking revamp. Now, when the player exits the game, they explicitly indicate that they are doing so and disconnect from the server. Previously, when leaving the game scene, the websocket connection remained open. When the game scene was loaded again, a new connection was established causing duplication.

I'll close this issue once we can confirm that the problem has been fixed.

**Comment by AtlantaDancer** [comment]
i think it was corrected.  I will confirm as I continue to test the leader board.  I'll let you know what I see.

**Comment by ignacioxd** [comment]
I think this has been fixed. I'm closing this issue, but we can reopen it if the problem resurfaces.
