### ISSUE TITLE
Players allowed to move out of arena

### ISSUE THREAD

**Issue by willhnation** [ignacioxd/ragin-mages#98]
In one of my first matches I was able to move my sprite out of the grid and into the surrounding black area. Eventually the AI could also follow me outside.

**To Reproduce**
Move sprite to the upper right hand corner of the arena. Try attacking a few times and then move sprite up and down. Return to the upper right hand corner and you should be able to move off grid

**Comment by adnanusman** [comment]
Hi, this is a known issue but it was not put into the issues list, thanks for doing that. Join us in the #game_projects section on slack.

**Comment by ignacioxd** [comment]
For anyone who'd like to work in this, the solution to this issue involves creating a new map using [Tiled](http://www.mapeditor.org/) will multiple layers. One of the layers should be the collision layer, and should be loaded as such in the game.

Here's an [example in Phaser 2](http://pixelgameart.org/web/portfolio/tiny-rpg-forest/), so we need to figure out if this same approach works on Phaser 3, and if not, what is the best way to do it in the newer version.

**Comment by BrianFreemanAtlanta** [comment]
FYI: My pull request adjusts the velocity for map edges.  This keeps the character, name and health bars together.  I tested if we take off the collision in the dungeon map it works for single player too.
